name: NexusCIA

on: workflow_dispatch

concurrency:
  group: ${{ github.workflow }}-${{ github.event.issue.number || github.run_id }}
  cancel-in-progress: true

jobs:
  Nexus3DS:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitarm:latest
    steps:
      - uses: actions/checkout@v3
      - name: Install build requirements
        run: |
          apt update
          apt install ninja-build
      - name: Download and install dependencies
        run : |
          apt install build-essential git libsdl2-dev libvorbis-dev libogg-dev libtheora-dev -y   
      - name: Build Sonic Nexus for the Nintendo 3DS
        run: make cia Makefile.3ds             
