# This is a basic workflow to help you get started with Actions

name: Build Sonic Nexus

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ vita ]
  pull_request:
    branches: [ vita ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  psvita:
    runs-on: ubuntu-latest
    container: vitasdk/vitasdk:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: apk add --no-cache make cmake git pkgconf
      - name: Build SDL2
        run: |
          git clone https://github.com/Northfear/SDL     
          cd SDL
          git checkout master
         cmake -S. -Bbuild -DCMAKE_TOOLCHAIN_FILE=${VITASDK}/share/vita.toolchain.cmake -DCMAKE_BUILD_TYPE=Release -DVIDEO_VITA_VGL=ON
         cmake --build build -- -j$(nproc)
         cmake --install build
      - name: Get and compile libtheora
        run: |
          mkdir -p dependencies/vita
          wget https://downloads.xiph.org/releases/theora/libtheora-1.1.1.tar.bz2 && \
          tar -xf libtheora-1.1.1.tar.bz2 -C dependencies/vita && \
          mv dependencies/vita/libtheora-1.1.1 dependencies/vita/libtheora
          cd dependencies/vita/libtheora
          ./configure --host=arm-vita-eabi --prefix=${VITASDK}/arm-vita-eabi --disable-shared --enable-static --disable-spec --disable-examples
          make install
      - name: Build Sonic Nexus
        run: |
          cd Nexus.vita
          cmake .
          make
      - name: Upload VPK
        uses: actions/upload-artifact@v2
        with:
          name: SonicNexus-vita
          path: Nexus.vita/SonicNexus.vpk
          if-no-files-found: error
