name: Build Sonic Nexus

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ 3ds ]
  pull_request:
    branches: [ 3ds ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.issue.number || github.run_id }}
  cancel-in-progress: true

jobs:
  Nexus3DS:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkitarm:latest
    steps:
      - uses: actions/checkout@v3
      - name: Install build requirements
        run: |
          apt update
          apt install ninja-build
      - name: Download and install dependencies
        run : |
          apt install build-essential git libsdl2-dev libvorbis-dev libogg-dev libtheora-dev -y   
      - name: Build Sonic Nexus for the Nintendo 3DS
        run: make -f Makefile.3ds                   
